# Generated by Django 4.0.4 on 2022-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_alter_project_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='urlField',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
